### PR TITLE
Budget App

### PR DESCRIPTION
**Pull request by Joel-100**
In this capstone project, the following tasks were completed:

-  Created a new rails app and set it up with PostgreSQL.
-  Setup linters
-  Installed rspec and capybara for testing.
-  Generated the user, group, expense and group_expense models.
-  Implemented the associations between the models.
-  Validated each model attributes.
-  Generated controllers for the user, group, expense and group_expense models.
-  Added the routes to the various views of the controllers.
-  Implemented authentication using devise.
-  Created a splash screen to display the logo of the app and include buttons to the login and sign up pages.
-  Created and styled the login and sign up pages.
-  Created the homepage to display all the categories created by the current user.
-  For each category, the user is allowed to view all transactions for the category and see the total amount for the category.
-  Added a button to allow the user to add new categories.
-  Created the transactions page to display all transactions of a particular category.
-  For each transaction, the user sees the name and amount of the transaction.
-  Added a button to allow the user to add transactions to the specific category.
-  Added a navigation bar.
-  Added specs for the application.
-  Documented the application with an updated README file.
-  Deployed the app.
-  Added a video presentation to the README file.

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @Joel-100, Can you please add content for all sections in your readme, please remember that all sections is required in your readme except the FAQ's

**Comment by Joel-100** [comment]
Yah sure thanks Priscilla,let me fix that!

**Comment by prolajumokeoni** [comment]
Hi @Joel-100 can you please reopen the pr?

**Review by prolajumokeoni — APPROVED** [review]
Hi @Joel-100 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
 - Deployed app link works perfectly ✅ 
 - List of transactions is presented ordered by the most recent 👏🏿 
 - Your app design matches the original design 🥇  
 - Devise is used for authentication 💪🏿 



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Kindly make sure when recording future presentation videos you follow the project requirements guidelines and answer them sequentially so you don't miss any point 👍🏿 
- It would be better to delete all placeholder texts in your readme, this will make your readme more professional 🤗 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Joel-100** [comment]
Thanks @prolajumokeoni

**Pull request merged**
